### ISSUE TITLE
sleep 10  +  ctrl+C

### ISSUE THREAD

**Issue by Ghasus** [filipbal/minishell-team#61]
minishell$ sleep 20
^C
minishell$ minishell$ 

Double prompt!!!

**Comment by filipbal** [comment]
I tried letting "sleep" complete and also interrupt with ctrl+c, but I don't see a double prompt, maybe was fixed in another issue..

<img width="163" height="93" alt="Image" src="https://github.com/user-attachments/assets/6b97bdde-3cc5-4f87-8aa3-7bc4b983d338" />

**Comment by Ghasus** [comment]
Now sleep does NOT work at all. It gives the prompt back right away.

**Comment by filipbal** [comment]
last commit broke command execution, reverted back one commit, so sleep works again, please check if you see double prompt

**Comment by Ghasus** [comment]
It is still not working as supposed (bash) with ctrl-C - it adds a prompt and alsp prints ^C, while in other cases ^C is not printed.

```
minishell$ sleep 10

minishell$ ^C
minishell$ 
```

**Comment by filipbal** [comment]
close enough :)
